### ISSUE TITLE
Pump duration in ms from water volume in ml

### ISSUE THREAD

**Issue by tomav** [Emilostuff/PlantKeeper#1]
Hi @Emilostuff, first of all thanks for your project, very close from what I wanted to do.
I just have 1 question about what you said in your video regarding water volume.
You came up with a formula like:

```
time_on = volume[mL] * flow_rate[ms/mL] + pipe[ms]
```

Can you explain the value for flow rate and pipe?

Thanks again!

**Comment by Emilostuff** [comment]
Hi! It is simply a linear relationship with an offset. When you start the pump it takes some time for the water to travel through the pipe. The water in the pipe will travel back to the reservoir when the pump stops. Hence we must fill the pipe first before any water comes out the other end. From there there is an approximate linear relationship between how long you leave the pump on and how much water is dispensed. As you will have seen in the video the exact values was found experimentally and will not deliver exact results, but merely some that are good enough :)

Hope this clarifies it!
